"use client";
import {useMemo,useState} from "react";

type M={id:string;full_name:string;phone_number:string;email:string;ic_number:string;umno_member_no:string;ipt_name:string;graduation_year:number;ipt_zone:string;umno_division:string;status:"pending"|"approved"|"rejected";membership_id:string|null};

export default function AdminPage(){
 const [members,setMembers]=useState<M[]>([]),[key,setKey]=useState(""),[ok,setOk]=useState(false),[msg,setMsg]=useState(""),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(false);
 async function load(k=key){setLoading(true);setMsg("");const r=await fetch("/api/admin/applications",{headers:{"x-admin-key":k}});const d=await r.json();setLoading(false);if(!r.ok){setOk(false);setMsg(d.error||"Gagal.");return}setMembers(d.members||[]);setOk(true)}
 async function change(id:string,status:"approved"|"rejected"){if(!confirm(`Teruskan ${status}?`))return;setLoading(true);const r=await fetch("/api/admin/applications",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify({id,status})});const d=await r.json();setLoading(false);if(!r.ok){setMsg(d.error||"Gagal.");return}setMsg(status==="approved"?`Diluluskan${d.member?.membership_id?` — ${d.member.membership_id}`:""}.`:"Ditolak.");await load()}
 const shown=useMemo(()=>members.filter(m=>(filter==="all"||m.status===filter)&&([m.full_name,m.email,m.phone_number,m.umno_member_no,m.ipt_name,m.ipt_zone,m.umno_division,m.membership_id||""].join(" ").toLowerCase().includes(q.toLowerCase()))),[members,q,filter]);
 const mask=(x:string)=>{const d=x.replace(/\D/g,"");return d.length>=4?`******-**-${d.slice(-4)}`:"****"};
 if(!ok)return <div className="form-wrap"><span className="eyebrow">Admin UMNOSiswa</span><h2>Login Pentadbir</h2><div className="form-card"><div className="field"><label>Admin Key</label><input type="password" value={key} onChange={e=>setKey(e.target.value)}/></div><button className="btn btn-primary" style={{marginTop:18}} disabled={!key||loading} onClick={()=>load(key)}>{loading?"Menyemak...":"Masuk Dashboard"}</button>{msg&&<div className="status err">{msg}</div>}</div></div>;
 return <div className="dashboard-shell"><div className="dash-header"><div className="container"><strong>Admin UMNOSiswa</strong></div></div><div className="container" style={{padding:"28px 0"}}>
 <div className="kpi-grid"><div className="kpi"><span className="small">Jumlah</span><strong>{members.length}</strong></div><div className="kpi"><span className="small">Pending</span><strong>{members.filter(m=>m.status==="pending").length}</strong></div><div className="kpi"><span className="small">Approved</span><strong>{members.filter(m=>m.status==="approved").length}</strong></div></div>
 <div className="panel"><h2>Permohonan Keahlian</h2><div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:18}}><input placeholder="Cari ahli..." value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button className="btn btn-outline" onClick={()=>load()}>Refresh</button></div>{msg&&<div className="status ok">{msg}</div>}
 <div style={{overflowX:"auto"}}><table><thead><tr><th>Nama</th><th>IC</th><th>No. UMNO</th><th>IPT</th><th>Zon</th><th>Bahagian</th><th>Status</th><th>ID</th><th>Tindakan</th></tr></thead><tbody>{shown.map(m=><tr key={m.id}><td><strong>{m.full_name}</strong><div className="small">{m.email}</div></td><td>{mask(m.ic_number)}</td><td>{m.umno_member_no}</td><td>{m.ipt_name}<div className="small">Tamat {m.graduation_year}</div></td><td>{m.ipt_zone}</td><td>{m.umno_division}</td><td><span className="badge">{m.status}</span></td><td>{m.membership_id||"—"}</td><td>{m.status==="pending"?<div style={{display:"flex",gap:8}}><button className="btn btn-primary" onClick={()=>change(m.id,"approved")}>Approve</button><button className="btn btn-outline" onClick={()=>change(m.id,"rejected")}>Reject</button></div>:<span className="small">Selesai</span>}</td></tr>)}</tbody></table></div></div></div></div>
}